ustbhuangyi/better-scroll

README.md
=> 完善了README.md

example/components/optional-demo/optionalDemo.vue, example/components/scroll/scroll.vue
=> finishpulldown时的回退同步

example/App.vue, example/components/input-option/inputOption.vue, example/components/optional-demo/optionalDemo.vue, example/components/scroll/scroll.vue, example/components/switch-option/switchOption.vue, example/pages/vertical-scroll/index.vue
add component input-option + add option threshold, stop
=> add component input-option + add option threshold, stop

example/components/input-option/input-option.vue, example/components/optional-demo/optional-demo.vue, example/components/scroll/scroll.vue, example/pages/vertical-scroll/index.vue
=> modify demo

example/common/js/config.js, example/components/scroll/scroll.vue, example/pages/vertical-scroll/index.vue
=> add demo: 处理下拉刷新上拉加载，没有新数据的情况

example/common/js/config.js, example/components/page/page.vue, example/components/picker/picker.vue, example/pages/picker/index.vue, example/pages/vertical-scroll/index.vue
add demo: 联动picker + 下拉加载文案option
=> add demo: 联动picker + 下拉加载文案option

example/common/js/config.js
=> demo: fix picker bug

example/components/picker/picker.vue, example/components/scroll/scroll.vue
=> fix picker bug

example/common/js/dom.js, example/components/scroll/scroll.vue
=> fix data too little bug

doc/en/api-specific.md, doc/en/api.md, doc/en/events.md, doc/en/options-advanced.md, doc/en/property.md
doc translate: from options-advanced to property
=> doc translate: from options-advanced to property

example/App.vue, example/language/english.js, example/pages/examples/index.vue, example/router/index.js
=> add router param language

example/language/english.js, example/pages/features/index.vue
=> optimize english

.github/ISSUE_TEMPLATE.md
=> translate issue template

doc/en/options.md, doc/zh-hans/options.md
add the description when probeType = 0
=> add the description when probeType = 0

types/index.d.ts, types/test.ts
https://github.com/ustbhuangyi/better-scroll/pull/317
=> typescript: do not export `default`

src/scroll/init.js, test/unit/specs/features/pull.js
=> fix relativeX relativeY computed error

types/index.d.ts
Add the following options to the `BsOption` interface in index.d.ts:
* `observeDOM`
* `autoBlur`
* `stopPropagation`
=> Add new options to BsOption in index.d.ts

types/index.d.ts, types/test.ts
主要的修改都是 @taoqf 提供的，我只是小幅修改了一下。谢谢。
合并后，ts工程就可以这么使用了：
`import BScroll from 'better-scroll';`
或者：
`import { BScroll, BsOption } from 'better-scroll';`
=> fix: type declaration

types/index.d.ts
=> scrollbar and mouseWheel missing options

README.md
I added a [jsDelivr CDN link](https://www.jsdelivr.com/) to the readme as an easier and faster option of using the project.  jsDelivr is the fastest opensource CDN available and has a big network in China too.
=> Add jsDelivr CDN link

packages/core/src/scroller/Scroller.ts
=> fix(scroller.ts): fix ios 13.4 bouncing

packages/pull-down/src/__tests__/index.spec.ts, packages/pull-down/src/index.ts
=> fix(pull-down): fix direction when two fingers touched, close #1055

packages/core/src/__tests__/__utils__/event.ts, packages/core/src/base/__tests__/ActionsHandler.spec.ts, packages/shared-utils/src/dom.ts
1. add touchcancel with eventTypeMap  
2. add test: touchcancel trigger the end event hook
=> fix(shared-utils): add touchcancel trigger the end event hook

packages/pull-up/src/index.ts, packages/vuepress-docs/docs/en-US/plugins/pullup.md, packages/vuepress-docs/docs/zh-CN/plugins/pullup.md
=> fix(pull-up): fix "pullingUp" event execution time

packages/vuepress-docs/docs/zh-CN/guide/use.md
=> 修复插件的链接是404的问题

packages/core/src/scroller/Actions.ts, packages/core/src/scroller/DirectionLock.ts, packages/indicators/src/indicator.ts, packages/mouse-wheel/src/index.ts, packages/scroll-bar/src/event-handler.ts, packages/shared-utils/src/dom.ts
=> fix: determine whether the cancelable property event can be canceled before preventDefault

packages/slide/src/PagesMatrix.ts, packages/slide/src/__tests__/PagesMatrix.spec.ts, packages/slide/src/constants.ts, tests/e2e/pulldown/sina.e2e.ts
fix: https://github.com/ustbhuangyi/better-scroll/issues/1318
=> fix(slide): PageStats does not return the default value
